Repository lxgr-linux/pokete, pull requests merged in 2022-06, with the labels that each got.

#123 Added time and improved some Poketes and Attacks
  gen_wiki.py
  pokete.py
  pokete_classes/achievements.py
  pokete_classes/attack_actions.py
  pokete_classes/buy.py
  pokete_classes/classes.py
  pokete_classes/deck.py
  pokete_classes/detail.py
  pokete_classes/dex.py
  pokete_classes/doors.py
  pokete_classes/effects.py
  pokete_classes/event.py
  pokete_classes/evomap.py
  pokete_classes/fightmap.py
  pokete_classes/game.py
  pokete_classes/general.py
  pokete_classes/generic_map_handler.py
  pokete_classes/input.py
  pokete_classes/landscape.py
  pokete_classes/learnattack.py
  pokete_classes/loops.py
  pokete_classes/movemap.py
  pokete_classes/moves.py
  pokete_classes/npcs.py
  pokete_classes/ob_maps.py
  pokete_classes/periodic_event_manager.py
  pokete_classes/poke.py
  pokete_classes/pokete_care.py
  pokete_classes/roadmap.py
  pokete_classes/side_loops.py
  pokete_classes/timer.py
  pokete_classes/types.py
  pokete_data/attacks.py
  pokete_data/map_data.py
  pokete_data/maps.py
  pokete_data/mapstations.py
  pokete_data/npcs.py
  pokete_data/poketes.py
  release.py
  wiki.md
Labels: enhancement

#125 Natures
  pokete_classes/detail.py
  pokete_classes/dex.py
  pokete_classes/nature.py
  pokete_classes/poke.py
  pokete_data/__init__.py
  pokete_data/natures.py
Labels: enhancement

#126 Bugfix
  pokete_classes/animations.py
  pokete_classes/classes.py
  pokete_classes/deck.py
  pokete_classes/detail.py
  pokete_classes/evomap.py
  pokete_classes/fightmap.py
  pokete_classes/game_map.py
  pokete_classes/movemap.py
  pokete_classes/side_loops.py
Labels: bug

#130 Edited grammar and spelling
  HowToPlay.md
  pokete.py
  pokete_classes/dex.py
  pokete_classes/fightmap.py
  pokete_classes/general.py
  pokete_classes/nature.py
  pokete_classes/npcs.py
  pokete_classes/poke.py
  pokete_data/attacks.py
  pokete_data/maps.py
  pokete_data/npcs.py
  pokete_data/poketes.py
  pokete_data/trainers.py
Labels: enhancement

#139 Small grammer/spelling of #138
  pokete_classes/effects.py
Labels: bug

#142 141 some wiki links dont work anymore
  gen_wiki.py
  wiki.md
Labels: bug

#140 Fixed Poketes not being freeable
  pokete_classes/deck.py
Labels: bug

#144 Fixed attacks missing and still giving effects
  pokete_classes/poke.py
Labels: bug

#168 Added more documentation for mods
  mods/README.md
  mods/__init__.py
Labels: documentation

#145 Balancing and Fight restructuring
  pokete.py
  pokete_classes/fightmap.py
  pokete_classes/landscape.py
  pokete_classes/npcs.py
  pokete_classes/poke.py
  pokete_classes/providers.py
  pokete_data/__init__.py
  pokete_data/attacks.py
  pokete_data/trainers.py
Labels: enhancement

#166 Fixes to decks freeing
  pokete_classes/deck.py
Labels: bug

#182 Fixed issue with moves
  pokete_classes/__init__.py
  pokete_classes/fightmap.py
Labels: bug

#208 Made input actions savable
  pokete.py
  pokete_classes/achievements.py
  pokete_classes/deck.py
  pokete_classes/detail.py
  pokete_classes/dex.py
  pokete_classes/fightmap.py
  pokete_classes/hotkeys.py
  pokete_classes/learnattack.py
  pokete_classes/movemap.py
  pokete_classes/nature.py
  pokete_classes/roadmap.py
  pokete_classes/timer.py
  pokete_classes/ui_elements.py
Labels: enhancement
